### ISSUE TITLE
Inflate XML.

### ISSUE THREAD

**Issue by kyogs** [dolphinwang/ImageCoverFlow#1]
Hello,Your demo application of cover flow really different from other and its same as i-phone gallery.Thanks to post this helpful code.Now i tried to inflate XML file but i cant achieved.Help me for that . 
Can i inflate xml file ?

Can i Stop looping mode ?

**Comment by rubenGuemez** [comment]
Hi, would you send me the example project? Thanks in advance :)

**Comment by ahsanSDq** [comment]
Hello, how can I use custom layout instead of images in coverflow?

**Comment by dolphinwang** [comment]
Hi，rubenGuemez，leave ur mail address plz~

**Comment by dolphinwang** [comment]
Sorry ahsanSDq.....Coverflow now only support the bitmap as image, so it can have better performance.

**Comment by ovokerie** [comment]
Nice library. Can you please send me a demo as I am getting an inflateException error my email is ovokerieogbeta@gmail.com .I really want to test this library
