### ISSUE TITLE
Demo required

### ISSUE THREAD

**Issue by hussnain** [dolphinwang/ImageCoverFlow#12]
Hi,
 i am facing issues will be great if u can send me the demo project 

hasnain@smonte.com

**Comment by AdamWorld** [comment]
I have also problem when making this work.
Would you please send me a demo project.

adamdev718@gmail.com

**Comment by rubenGuemez** [comment]
I have problems too. Could you send me the demo?
kukulkan_0707@hotmail.com

**Comment by sakurabird** [comment]
hi
Could you send me demo too?
thanks
neko3genki@gmail.com

**Comment by AdamWorld** [comment]
I have also problem when making this work.
Would you please send me a demo project.

adamdev718@gmail.com

**Comment by dolphinwang** [comment]
Sorry for reply late. Demo has been send to your mail-box.

**Comment by vaiiibhav** [comment]
hey can you please provide me demo.. vaiiibhav.pansambal@gmail.com
