### ISSUE TITLE
Changing child effect

### ISSUE THREAD

**Issue by mitko9000** [dolphinwang/ImageCoverFlow#14]
How can I achieve this effect for the center parent and the childs ?

![effecttwo](https://cloud.githubusercontent.com/assets/6358805/6695062/11f6a206-cce7-11e4-9a0a-5c0e01888e8c.png)
![effectone](https://cloud.githubusercontent.com/assets/6358805/6695057/0ee31fae-cce7-11e4-8c4c-113cf593c29e.png)

**Comment by dolphinwang** [comment]
Unlock annotated code in method “getCustomTransformMatrix”。But these code are for test, So if want to use. I advise that Make a new "Class" and extends from CoverFlowView, then override method "getCustomTransformMatrix".

**Comment by mitko9000** [comment]
Any exmaple,demo can you provide ?

**Comment by dolphinwang** [comment]
Sample code is just in method "getCustomTransformMatrix", annotated
