### ISSUE TITLE
XML problem it would't get loaded 

### ISSUE THREAD

**Issue by ramanecommstreet** [dolphinwang/ImageCoverFlow#16]
Included this on the top  (xmlns:imageCoverFlow="http://schemas.android.com/apk/res-auto"  )

<com.dolphinwang.imagecoverflow.CoverFlowView
        android:id="@+id/CoverFlow"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="30"
        android:paddingLeft="20dp"
        android:paddingRight="20dp" >
    </com.dolphinwang.imagecoverflow.CoverFlowView>

04-02 06:13:26.840: E/c**********.common.UnCaughtException(1490): java.lang.RuntimeException: Unable to start activity ComponentInfo{com******************/com*********.activity.PostDetailActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class com.dolphinwang.imagecoverflow.CoverFlowView

Plz help

**Comment by dolphinwang** [comment]
Plz tell me your e-mail address, I'll send demo project to you

**Comment by dolphinwang** [comment]
Plz tell me your e-mail address, I'll send demo project to you

**Comment by dolphinwang** [comment]
Plz tell me your e-mail address, I'll send demo project to you

**Comment by ramanecommstreet** [comment]
HI, it's ramannjinal@gmail.com. Thanks in advance.

**Comment by dolphinwang** [comment]
Oh, can you provide another mail address? Um...I can't send it to this mail-box...

**Comment by ramanecommstreet** [comment]
sorry, my bad, it's ramannjindal@gmail.com

**Comment by dolphinwang** [comment]
Ok, I send it~
