### ISSUE TITLE
[Question] Items less than 3

### ISSUE THREAD

**Issue by mitko9000** [dolphinwang/ImageCoverFlow#18]
Will you implement in future as feature for this library to work with one and two items only ?

**Comment by dolphinwang** [comment]
When item less than three(one or tow), sometimes it'll hard to layout. Not hard in code，but hard in sense of beauty I think。

**Comment by mitko9000** [comment]
@dolphinwang  Is there a way to animate the view when I am updating the adapter ?

**Comment by dolphinwang** [comment]
@mitko9000 You mean, you want to animate images when call invalidPosition?

**Comment by mitko9000** [comment]
@dolphinewang for example if you have up and down gesture to change coverflow items.
I want to animate the view while the user is executing the up/down gesture

**Comment by dolphinwang** [comment]
I see, if user select one of image, you want to make an animation to put the right image to the top. Am I right?

**Comment by mitko9000** [comment]
No,Imagine that you perform vertical down gesture with your finger on the coverflow and when that action is in progress do a animation that translate the whole coverflowview down to the bottom of the layout and invalidate the new loaded items on top.

**Comment by mitko9000** [comment]
@dolphinwang Or give any idea how to move up the center child always higher than the other ?

**Comment by Raju211** [comment]
@mitko9000  Did you find answer for items less than 3 ??
