### ISSUE TITLE
App crash with this error---->>total count in adapter must larger than visible images!

### ISSUE THREAD

**Issue by Raju211** [dolphinwang/ImageCoverFlow#22]
When i tried to display less than three images I got this error,Please help me how to solve the issue.

**Comment by mitko9000** [comment]
@Raju211 You can't the minimum of images you need to have in the adapter is three if you want less then that you have to implement custom transformation behavior.

**Comment by dolphinwang** [comment]
Yeah, like @mitko9000 said, can't put less than 3 images in cover flow, because lib will in trouble when calculate the location of images
