### ISSUE TITLE
getting an error on inflation of the coverflowview class

### ISSUE THREAD

**Issue by ovokerie** [dolphinwang/ImageCoverFlow#26]
E/c*******.common.UnCaughtException(1490): java.lang.RuntimeException: Unable to start activity ComponentInfo{com************/com******.activity.PostDetailActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class com.dolphinwang.imagecoverflow.CoverFlowView
Can you please send a demo to ovokerieogbeta@gmail.com. thanks in advance

**Comment by dolphinwang** [comment]
Hi the demo has been send to ur mail box
