### ISSUE TITLE
Project is out of date.

### ISSUE THREAD

**Issue by LittlePanpc** [dolphinwang/ImageCoverFlow#28]
When I cloned your project and copied sample codes from **ReadMe**, the project can't be compiled. It implied that `reflectionShaderEnable` and `enableReflection` are not included in your current project. So, would you update your `ImageCoverFlow` as soon as possible?

**Comment by dolphinwang** [comment]
Yeah，I will update it. And for now, plz remain ur e-mail, I'll send sample to you

**Comment by LittlePanpc** [comment]
@dolphinwang happychinapc@gmail.com

**Comment by dolphinwang** [comment]
Send demo already~

**Comment by LittlePanpc** [comment]
Thanks.

**Comment by dolphinwang** [comment]
Hey, now I push the newest project and sample code. You can try it~

**Comment by mitko9000** [comment]
What is the change in the new source code ?
