### ISSUE TITLE
CircleImageView

### ISSUE THREAD

**Issue by MasharipovF** [dolphinwang/ImageCoverFlow#30]
Hey, dolphinwang! Thank you for your great lib. I was wondering if i could use CircleImageView to display my data.

**Comment by mitko9000** [comment]
@MasharipovF  You can but you have to move all of your logic to manipulate the bitmap inside the CoverFlowView or somehow manipulate the images inside the adapter before the view request them.

**Comment by dolphinwang** [comment]
Yeah, U should do all on Bitmap and return it, this widget only accept bitmap
