### ISSUE TITLE
how to make the getImage  become loading online data

### ISSUE THREAD

**Issue by cosplay-wang** [dolphinwang/ImageCoverFlow#33]
i try to change that mothed  getimage   ,but  not worked. so i try to pass the url  into mAdapter.getImage(),
and  here not allow to async.   can you give some suggestions?

**Comment by dolphinwang** [comment]
Yeah，the method 'getImage' should return the bitmap object directly.

For load bitmap async, U can use 'adapter#notifyDataSetChanged' when ur online image have been downloaded.

So, U can download online images by any ways U like, and notify the CoverFlow to load it via 'adapter#getImage'.

Hope this can help U :)
