### ISSUE TITLE
occur a ANR 😭

### ISSUE THREAD

**Issue by xiaosongfu** [dolphinwang/ImageCoverFlow#37]
03-30 10:21:36.402 501-534/? E/ActivityManagerService: ANR in com.mogujie.coverflowsample (com.mogujie.coverflowsample/.MyActivity)
                                                       PID: 3195
                                                       Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 49.  Wait queue head age: 5512.6ms.)
                                                       Load: 1.06 / 1.09 / 0.89
                                                       CPU usage from 7153ms to 0ms ago:
                                                         81% 3195/com.mogujie.coverflowsample: 79% user + 2% kernel / faults: 139 minor
                                                         7.6% 703/com.android.systemui: 6.2% user + 1.3% kernel / faults: 4026 minor
                                                         6.9% 161/surfaceflinger: 2.6% user + 4.3% kernel / faults: 1797 minor
                                                         4.1% 155/logd: 4% user + 0.1% kernel
                                                         3% 501/system_server: 1.9% user + 1.1% kernel / faults: 396 minor
                                                         1.6% 976/com.ubtechinc.cruzr.launcher2: 0.9% user + 0.6% kernel / faults: 9 minor
                                                         0.6% 146/dhd_dpc: 0% user + 0.6% kernel
                                                         0.5% 113/ddrfreqd: 0% user + 0.5% kernel
                                                         0.5% 180/adbd: 0.1% user + 0.4% kernel
                                                         0.5% 2979/kworker/0:2: 0% user + 0.5% kernel
                                                         0.4% 120/kworker/u8:2: 0% user + 0.4% kernel
                                                         0.4% 547/logcat: 0% user + 0.4% kernel
                                                         0.2% 3151/logcat: 0.1% user + 0.1% kernel
                                                         0.1% 8/rcu_preempt: 0% user + 0.1% kernel
                                                         0.1% 44/fb-vsync: 0% user + 0.1% kernel
                                                         0.1% 45/rk-fb: 0% user + 0.1% kernel
                                                         0.1% 46/cfinteractive: 0% user + 0.1% kernel
                                                         0.1% 145/dhd_watchdog_th: 0% user + 0.1% kernel
                                                         0.1% 147/dhd_rxf: 0% user + 0.1% kernel
                                                         0% 151/jbd2/mmcblk0p12: 0% user + 0% kernel
                                                         0% 157/lmkd: 0% user + 0% kernel

**Comment by dolphinwang** [comment]
会不会是同步加载bitmap在UI线程耗费了太多时间？
